# Generated by Django 5.2.17 on 2026-08-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, help_text='A unique slug for the project.', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
